version: '3.8'

services:
  # Databases & Infrastructure Core
  postgres:
    image: postgres:15-alpine
    container_name: finguard-postgres
    environment:
      POSTGRES_DB: finguard_core
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: finguard-redis
    ports:
      - "6379:6379"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: finguard-qdrant
    ports:
      - "6333:6333"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: finguard-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: finguard-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Microservices
  gateway:
    build: ./gateway
    container_name: finguard-gateway
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - auth-service
      - user-service
      - fraud-service

  auth-service:
    build: ./auth-service
    container_name: finguard-auth-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finguard_core
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  user-service:
    build: ./user-service
    container_name: finguard-user-service
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finguard_core
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  fraud-service:
    build: ./fraud-service
    container_name: finguard-fraud-service
    ports:
      - "8083:8083"
    depends_on:
      - postgres
      - kafka
      - fraud-ml-engine
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finguard_core
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      AI_ML_SERVICE_URL: http://fraud-ml-engine:8000

  fraud-ml-engine:
    build: ./fraud-service/ml_engine
    container_name: finguard-fraud-ml-engine
    ports:
      - "8000:8000"

  notification-service:
    build: ./notification-service
    container_name: finguard-notification-service
    ports:
      - "8085:8085"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:29092
      PORT: 8085

volumes:
  pgdata:
